### PR TITLE
Serbian (sr and sr@latin) translation

### PR DESCRIPTION
**Pull request by Faenriis**
Please merge. Thanks.

### CODE REVIEW

**Comment by rmarquis** [comment]
Great, thank you!

Can you confirm that the `sr@latin` is correctly handled by gettext? 

In `/etc/locale.gen`, I see the following locales available:

```
sr_ME UTF-8
sr_RS UTF-8
sr_RS@latin UTF-8
```

**Comment by rmarquis** [comment]
Ah, I see this is also done the same in pacman translation. Sorry for the dumb question. Merging.

**Comment by Faenriis** [comment]
Actualy, can be either (sr or sr_RS, and sr@latin or sr_RS@latin - @something refers to used writing, in this case latin script, as opposed to default cyrillic), but was following your guidelines which say "use the 'short' locale (de, es, fr, ...) to make it available to all sublocales".  So, it's entirely up to you, all defined in gettext and glibc, and both will handle it either way. :)
Thanks for merging!

**Comment by rmarquis** [comment]
Pacman does it the way you've done it, so I guess that's perfect!
This will be included in the next 4.6.2 release, available in a few days.

**Pull request merged**
