### PR TITLE
Quote $builddir

### PR DESCRIPTION
**Pull request by davispuh**
Need to quote $builddir so that spaces are preserved.

### CODE REVIEW

**Comment by rmarquis** [comment]
Why would you use a directory name with a space? Just curious...

**Comment by davispuh** [comment]
Because why not? :D It's same character like any other so there can be folders like "AUR Packages" :P

**Comment by rmarquis** [comment]
It's be considered bad practice on UNIX..
I'll probably need to check the entire code for this "issue".

**Comment by davispuh** [comment]
It works fine with this fix, I didn't encounter other issues so probably everywhere else it's already quoted. And I bet it's bad practice only because a lot of shell scripts doesn't quote and thus break. But really there aren't any legitimate reason why couldn't.

**Comment by rmarquis** [comment]
No, it's [more subtle](http://www.dwheeler.com/essays/fixing-unix-linux-filenames.html#spaces) than this.
Supporting space in filename doesn't really make sense, but if this is to be done then I'll need more than a "my own workflow works with that patch, so it probably works everywhere". I'll check the entire code when I get time.

**Comment by rmarquis** [comment]
The only other part of the code where builddir isn't quoted is right above your change. It has been reverted in the following commit https://github.com/rmarquis/pacaur/commit/4413f6febffa178e4fd1eca9e9b361695cb2c13a as it breaks the code when using "-cc" without extra arguments for cleaning the builddir (see #333).

**Comment by davispuh** [comment]
I missed that because searched only for `$builddir`... anyway current code is wrong, if I've unrelated folder `/var/AUR` and `BUILDDIR="/var/AUR Packages"` then `pacaur -cc` will remove `/var/AUR`
I just updated PR to fix this.

**Comment by rmarquis** [comment]
Merged both patches and pushed to master. Thank you!

**Pull request closed without merging**
