### PR TITLE
fixes issue https://github.com/rmarquis/pacaur/issues/681

### PR DESCRIPTION
**Pull request by steadfasterX**
Could you please look into this? It works for me and was an easy fix for my problem..

### CODE REVIEW

**Comment by rmarquis** [comment]
This is a cheap workaround that doesn't fix the underlying issue. Not merging, but I suggest you keep it in a local branch while the main issue is being worked on.

**Comment by steadfasterX** [comment]
correct this does not solve the problem regarding IgnorePkg merge but it fixes the issue that one cannot choose a custom config file.

so should I open a new issue that one cannot add a custom config file and point this PR to it?

**Comment by rmarquis** [comment]
No, because as I pointed out, this is a workaround, not a fix. The underlying issue is tracked in #433.

**Comment by steadfasterX** [comment]
No what I wanted to say is:

pacaur misses the option "--config" like pacman has.

this has **nothing to do with ignorepkg** and is a complete **other** issue.
The --config option gets **not** tracked by #433 .

**Comment by ChuckDaniels87** [comment]
@steadfasterX In the end, it is the same topic that it is shown in #433. I think it is better to find a complete solution and not workarounds for each issue derived from the same problem.

**Comment by rmarquis** [comment]
Yes, exactly. Moreover, `--config` could apply equally to pacman, makpekg or pacaur config files. This isn't straightforward to implement.  I have also no idea what a clear user case for that flag would be.

**Comment by steadfasterX** [comment]
@ChuckDaniels87 
this is no workaround. 
pacaur does not support the `pacman --config` option
the PR adds this option.

@rmarquis 
my usecase is that I want to have different output for different usage scenarios and or different options for different users.
btw: you could ask why is that implemented in pacman as well ;)

> could apply equally to pacman, makpekg or pacaur config files

sorry I don't get u. the option --config is available for pacman so yes it should apply there as well.

**Comment by rmarquis** [comment]
To do what, exactly? You're running around XY problem here.

**Comment by steadfasterX** [comment]
I share the PC with several users:

me the full admin and "normal users"

When I use pacaur i need complete different (therefore not merged) options for:

```
HoldPkg
IgnorePkg
CleanMethod
```

as the normal users would have. A normal user should be able to upgrade the system but e.g. not for the kernel.

Example normal user conf: 
```
[options]
IgnorePkg= linux-lts foo bar
```

Example admin user conf:
```
[options]
IgnorePkg = 
```

Each user will have an alias for _pacaur_ pointing to `pacaur --config "normal user conf"`.

**Comment by rmarquis** [comment]
So partial update? Hardly a valid user case, and in any case out of scope of the intended design.

**Comment by steadfasterX** [comment]
just an example. `CleanMethod` has nothing to do with partial upgrade

**Comment by rmarquis** [comment]
You just convinced me that letting some user handling packages and other only a subset of them is a crazy, stupid idea. Well, actually that's what I thought already, but you perfectly illustrated that your user case is not something pacaur should support.

**Comment by steadfasterX** [comment]
lol. so please remove it from pacman and yaourt as well ;)
your software your choice.

**Comment by ChuckDaniels87** [comment]
I think that config option can be implemented on `pacaur` using properly `pacconf`. That is the correct way in my opinion (#433).

>as the normal users would have. A normal user should be able to upgrade the system but e.g. not for the kernel.

> lol. so please remove it from pacman and yaourt as well ;)

In any case, the user case that you suggested is totally [unsupported on ArchLinux and strongly discouraged](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported).  The existence of config option is obviously not intended to be used on the user case you suggested.

**Comment by steadfasterX** [comment]
> In any case, the user case that you suggested is totally unsupported on ArchLinux and strongly discouraged. The existence of config option is obviously not intended to be used on the user case you suggested.

I know that partial upgrades are not supported.

best example: Thunderbird + Lightning just a few days ago. Due to a change my mozilla to include lightning into thunderbird breaks the calendar completely on my system so I downgraded and set the package to ignore list. This is what I want to do for my "normal users".

This is the only way to solve issues like these and still keeping my system up2date..

Let's say that issue gets fixed in 3 weeks. that would mean to not get any update until then. Thats maybe ok for some but not for me.

**Comment by ChuckDaniels87** [comment]
>best example: Thunderbird + Lightning just a few days ago. Due to a change my mozilla to include lightning into thunderbird breaks the calendar completely on my system so I downgraded and set the package to ignore list. This is what I want to do for my "normal users".

So, your users can break other users packages to workaround issues on their packages. If partial upgrade from system admin is unsupported and discouraged, letting "normal users" to upgrade, downgrade and ignore package at system level is a perfect recipe for disaster. 

You should look other solutions that support install packages on a per-user basis: flatpak, snap, appimage, spack, pip, etc.

**Comment by steadfasterX** [comment]
ok. then just tell me why IgnorePkg does exists?

**Comment by rmarquis** [comment]
> I think that config option can be implemented on pacaur using properly pacconf. That is the correct way in my opinion (#433).

Yes. Now please either work on #433 and stop wasting my time.

**Comment by ChuckDaniels87** [comment]
> ok. then just tell me why IgnorePkg does exists?

Just read the wiki, I've even put the link above for you.

> That is why partial upgrades are not supported. Do not use pacman -Sy package or any equivalent such as pacman -Sy followed by pacman -S package. Always upgrade (with pacman -Syu) before installing a package. **Be very careful when using IgnorePkg and IgnoreGroup for the same reason**. If the system has locally installed packages (such as AUR packages), users will need to rebuild them when their dependencies receive a soname bump.  

I suggested you other proper package managers for your user case. 

Anyways, I think this is not the place to have a discussion about ArchLinux and `pacman` design. If you want to continue talking about this, you can create a thread on ArchLinux Forums or join official IRC channel.

**Comment by steadfasterX** [comment]
> Just read the wiki, I've even put the link above for you.

As said I know that article. 
The wiki do not contain an answer to my question why or for what IgnorePkg does exists (if not for doing partial upgrades in a valid scenario). 

But anyways. You have already made your decision - for your own reasons - to not include a valid option (--config) which exists in pacman. 
That's bad for us but that's the way it goes. The discussion about the pro and contra doing partial upgrades and the risk this could have is nothing I wanted to have here. 

I just wanted to add a feature available in pacman for pacaur which I believe makes totally sense (and you not). 

story end.

**Pull request closed without merging**
