### PR TITLE
Allow y/n in prompt, add Finnish translation

### LINKED ISSUE #436: "Proceed with installation? [Y/n]" wants K or E instead.
I use Arch in Finnish and when I installed pacaur, I was confused on why it just quit when I answered `y` or `n`. Then I tried `k` and the installation continued and later `e` so it was aborted.

K is Kyllä (Yes in Finnish) and E is Ei (No in Finnish).

I think pacaur should either accept Y/n as input or ask for what it really wants.
- pacaur 4.5.4-1 installed from the AUR
- Arch Linux

### PR DESCRIPTION
**Pull request by durazell**
Attempt to fix #436.

### CODE REVIEW

**Comment by rmarquis** [comment]
I'll integrate the Finnish translation, but I'm not able to take the second patch. See [pacman-dev](https://lists.archlinux.org/pipermail/pacman-dev/2016-November/021663.html).

**Comment by rmarquis** [comment]
Are you sure you've updated pacaur.pot before translating it? I don't see the latest strings that were added.

**Comment by durazell** [comment]
I used de.po for initial translation and then ran commands here https://github.com/rmarquis/pacaur/blob/master/po/HOWTO.

$ cd ./pacaur
$ bash --dump-po-strings pacaur > pacaur.pot
$ msguniq pacaur.pot > pacaur.po
$ msgmerge --update po/fi.po pacaur.po

I'll look it later today, once i get home.

**Comment by rmarquis** [comment]
@durazell: any news on this? I hope to release the next update in a couple of days.

**Comment by rmarquis** [comment]
Merged the partial translation.

**Pull request closed without merging**
