### PR TITLE
Style and meaning changes to Slovak translation.

### PR DESCRIPTION
**Pull request by DoctorJellyface**
Please create a hotfix for this, as the old translation sometimes had a completely different meaning than the original. I also made a lot of style, grammar, readability and indenting changes. Also fixed whitespaces.

Thanks @pakapusta for the work!

### CODE REVIEW

**Comment by rmarquis** [comment]
Thanks for your input!

@pakapusta Can you check the above commit? I'm certainly not in a position to validate proposed change to your original translation.

Also, I don't do "hotfix" for translation issues, you'll have to wait for the next regular release.

**Comment by DoctorJellyface** [comment]
@pakapusta na zdôvodnenie mojich zmien: preklad raz tykal, raz vykal, raz za čas používal čechizmy alebo zlé preklady, tiež som menil slovosled tam kde to lepšie sedelo a zjednodušil som veci ako cie(ľ)(ov), čo sa fakt blbo čítalo, na cieľ(ov), podobne ako to urobili v preklade pacmana. A takisto som sa snažil vyhnúť skloňovaniu neskloňovateľných cudzích slov a občas som slovenské nahradil cudzím aby bol jasnejší význam, šak predsa ide o systémy, nie o slovenčinu ;)

**Comment by DoctorJellyface** [comment]
@rmarquis I was asking for a minor version release because there was a bit of a chaos with the translation of strings regarding removal of files, along with other stuff.

**Comment by rmarquis** [comment]
Well, it is a shame that you narrowly missed the last release by 1 hour or so, but you still have to wait for the next regular release. I do however expect it happening quite soon (few days), since changes are consequent and I wouldn't be surprised it introduced a few regressions.

**Comment by DoctorJellyface** [comment]
@rmarquis I only noticed it after updating pacaur though ;)

**Comment by pakapusta** [comment]
@rmarquis I agree with all proposed changes, this guy is much more experienced in translating than me.

@DoctorJellyface Thank you very much for checking ang corrections.

**Comment by rmarquis** [comment]
Thanks, merged!

**Comment by DoctorJellyface** [comment]
@pakapusta @rmarquis I wouldn't say I'm more experienced, I only translated a few things so far, but I was lucky enough to live a few years in England and I'm a damn perfectionist ;)

**Pull request merged**
