### PR TITLE
slovak translation

### PR DESCRIPTION
**Pull request by pakapusta**

### CODE REVIEW

**Comment by rmarquis** [comment]
Thanks. Since you closed this pull request, do you actually want me to merge this translation? Or did you close it on purpose?

**Comment by pakapusta** [comment]
Sorry, this is my first ever pull request, i would be pleased if you merge my translation.

**Comment by rmarquis** [comment]
No worries, merging now. Thanks for your work!

**Comment by DoctorJellyface** [comment]
Oh come on, I had this semi-done! Ah well.

**Pull request merged**
