### PR TITLE
Structure code with banners

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
I've made this Pull Request as a first approach. This shows some ideas about improving source code readability (see #443). I did not modify any function or operation, just commentaries.

* Structure code with three types of banners commentaries. Divide
  source in four clear sections:
  * Heading
  * Configuration and Variables
  * Functions
  * Main.

* Subdivide each category into little code parts.

* Capitalize first letter of all commentaries.

* Move VIM configuration hint to heading.

* Add license to heading (just an idea).

### CODE REVIEW

**Comment by AladW** [comment]
Wouldn't it be better to use one or two descriptive sentences per function, rather than big banners with just a few words? [Simple example](https://github.com/AladW/aurutils/blob/master/aurqueue#L7)

**Comment by rmarquis** [comment]
Yes, banners hardly add anything but clutter the whole file. Vim settings at the bottom is very common, and using lower cases for comments is just my personal preference that I won't change soon. I'll however introduce the license at the top of the file once I'm sure there are no more GPL code left (see #430).

**Comment by ChuckDaniels87** [comment]
This pull request was meant only to show you some ideas. Coding style is a very personal stuff, I prefer to be very verbose in commentaries and I usually give a visual styling to my code. I'll try to stick to your taste about this. 
What do you about making a short code style-guide to ease contributions and fit into your coding preferences?

**Comment by ChuckDaniels87** [comment]
Well, this made me look for some style guides and check some open source projects styles. I've realized that I usually over-comment my code, I clutter it. I just want to thank you because your comments just made me improve my programming skills a bit. :+1:

**Pull request closed without merging**
