### PR TITLE
New structure

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
First code splitting. I've organized the functions as it follows:
- _main.sh.in:_ core functions and top-level stuff. 
- _pkgs.sh.in:_ package related functions. 
- _deps.sh.in:_ dependency related functions.
- _cache.sh.in:_ cache related functions.
- _info.sh.in:_ info related functions.
- _utils.sh.in:_ utility functions like messages, etc.
- _checks.sh.in:_ group all checkings together.

I've sourced all theses files from the main script. If you want to test it locally you can change `functiondir` from `/usr/share/pacaur` to `./libpacaur`. Obviously PKGBUILD must be changed to properly install `pacaur` with these changes.

I need some feedback about this organization.

### CODE REVIEW

**Comment by rmarquis** [comment]
My only complaint so far is that the `.in` extension is specific to cmake (as stated by Alad in #443), which doesn't make sense here. Could you rename these files? Then it's all green for me.

**Comment by ChuckDaniels87** [comment]
Done!

**Comment by rmarquis** [comment]
I think you also need to adjust the main pacaur file for new paths :)

**Comment by ChuckDaniels87** [comment]
I was fast... nobody saw it. :P

**Pull request merged**
